import 'dart:math' as math;

import 'package:auto_size_text/auto_size_text.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_svg/svg.dart';
import 'package:popover/popover.dart';
import 'package:schoolap_ui/schoolap_ui.dart';
import 'package:schoolap_ui/src/utils/custom_tydef.dart';
import 'package:flutter_svg/flutter_svg.dart';

part 'base/app_card.dart';
part 'base/app_icon.dart';
part 'base/app_text.dart';
part 'base/dot_container.dart';
part 'base/schoolap_app_chip.dart';
part 'base/schoolap_illustration_container.dart';
part 'app_button/sp_button_primary.dart';
part 'app_button/state_primary_button.dart';
part 'app_button/state_secondary_button.dart';
part 'app_field/school_app_drop_down.dart';
part 'app_field/school_app_drop_down_presence.dart';
part 'app_field/school_app_text_field.dart';
part 'app_field/schoolap_presence_dropdown.dart';
part 'card/schoolap_card_alert.dart';
part 'card/schoolap_card_presence.dart';
part 'card/schoolap_card_tile.dart';
part 'card/schoolap_card_with_image.dart';
part 'appbar/schoolap_main_appbar.dart';
part 'appbar/schoolap_appbar.dart';
part 'data_table/schoolap_pagination.dart';
part 'card/schoolap_pop_menu_button.dart';
part 'card/custom_pop_up.dart';
part 'app_field/schoolap_radio.dart';
